name: Linux

on: 
  push:
    branches:
      - mine
  pull_request:
    branches:
      - master
    remote: upstream
jobs:
  release: 
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libfreetype-dev
      - name: configure
        run: cmake -D CMAKE_BUILD_TYPE=Release -B build
      - name: build
        run: cmake --build build -j $(nproc --all)
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Source/libOsiris.so
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}